services:
  mysite:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./mysite:/mysite
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  postgres_data: