services:
  mysite:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/mysite/static_files
      - media_volume:/mysite/media_files
    expose:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTSGRES_PASSWORD=${POSTGRES_PASSWORD}

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/mysite/static_files
      - media_volume:/mysite/media_files
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysite

  certbot:
    build:
      context: ./certbot
    command: echo "Skipping..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN=${DOMAIN}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
