services:
  mysite:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/mysite/static_files
      - media_volume:/mysite/media_files
    expose:
      - 8000:8000
    env_file:
      - ./deploy.env
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./deploy-db.env

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/mysite/static_files
      - media_volume:/mysite/media_files
    ports:
      - 1337:80
    depends_on:
      - mysite

volumes:
  postgres_data:
  static_volume:
  media_volume:
