name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    env:
      DJANGO_DEBUG: 1
      SECRET_KEY: change_me
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: postgres
      SQL_USER: postgres
      SQL_PASSWORD: test
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
      POSTGRES_PASSWORD: test
      ACME_DEFAULT_EMAIL: email@example.com
      DOMAIN: localhost

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.5.0
      with:
        cache: pip
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./mysite
      run: |
        python manage.py test
        
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd blog
          git pull
          docker compose -f docker-compose-deploy.yml up -d --build
