name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    env:
      DJANGO_DEBUG: 1
      SECRET_KEY: change_me
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: postgres
      SQL_USER: postgres
      SQL_PASSWORD: test
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
      POSTGRES_PASSWORD: test
      ACME_DEFAULT_EMAIL: email@example.com
      DOMAIN: localhost

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./mysite
      run: |
        python manage.py test
        
  deploy:
  
    runs-on: self-hosted
    
    steps:
      - run: |
          ls
